base_path: /
routes:
  index: [/,App\Controllers\homeController.index,GET]
  parse: ['/parse',App\Controllers\homeController.parse,GET]
  partials: ['/partials/:name',App\Controllers\apiController.partial,GET]
  builder: ['/builder',\Core\Builder.index,GET]
  create_builder: ['/builder/create',\Core\Builder.create,POST]
  create: ['/',create,'POST']
  update: ['/:id',update,'POST']
  new: ['/new',new,'GET']
  products_index: ['/products',\App\Controllers\ProductsController.index,'GET']
  edit: ['/edit/:id',edit,'GET']
  delete: ['/destroy/:id',destroy,'GET']











