base_path: /
routes:
  #home
  auth: [/auth,\App\Controllers\homeController.auth,GET]
  index: [/,App\Controllers\homeController.index,GET]
  accounts: [/accounts,\App\Controllers\homeController.listAccounts,GET]
  list_checks: [/checks,\App\Controllers\homeController.listChecks,GET]
  convert: [/convert,\App\Controllers\homeController.convert,POST]
  rc: [/changes,\App\Controllers\homeController.reportCorrection,POST]
  # agents
  get_agents : [/agents,App\Controllers\agentsController.index,GET]
  get_collectors: ['/collectors',App\Controllers\agentsController.getCollectors,GET]
  
  # clients
  get_client_list: [/clients/list,App\Controllers\clientsController.index,GET]
  update_client_profile: [/clients/:id/update,App\Controllers\clientsController.updatePolicy,PUT]
  show_client: [/clients/show/:id,App\Controllers\clientsController.profile,GET]
  create_policy: [/clients/policies/create,\App\Controllers\clientsController.createPolicy,POST]
  get_client_profile: [/clients/:id,App\Controllers\clientsController.show,GET]
  create_client: [/clients/create,App\Controllers\clientsController.create,POST]
  create_bulk_clients: [/clients/bulk,App\Controllers\clientsController.bulk,POST]
  # payments
  create_payment: [/payments/create,\App\Controllers\paymentsController.create,POST]
  get_payment_list: [/payments,\App\Controllers\paymentsController.index,GET]
  get_payment: [/payments/:id,\App\Controllers\paymentsController.getClientPayments,GET]
  validate_payment: [/payments/validate/:id,\App\Controllers\paymentsController.validate,GET]
  # reports
  get_reports_list: [/reports,\App\Controllers\reportsController.getReports,GET]
  test: [/test,\App\Controllers\homeController.test,GET]
  movements: [/movements/:id,\App\Controllers\reportsController.accountMovements,GET]
  # expenses
  get_expenses_list: [/expenses,\App\Controllers\expensesController.index,GET]
  create_expense: [/expenses,\App\Controllers\expensesController.create,POST]
  create_policy_payment: [/payments/policy,\App\Controllers\expensesController.CreatePolicyPayment,POST]
  get_policy_payments: [/payments/policy/:id,\App\Controllers\expensesController.getPolicyPayments,GET]
  # operations
  create_transfer: [/transfers,\App\Controllers\operationsController.createTransfer,POST]
  collect_check: [/checks/collect,\App\Controllers\operationsController.collect_check,POST]
  register_income: [/income,\App\Controllers\operationsController.createIncome,POST]
  # categories
  create_category: [/categories,\App\Controllers\categoriesController.create,POST]
  update_category: [/categories/:id,\App\Controllers\categoriesController.update,PUT]
  list_categories: [/categories,\App\Controllers\categoriesController.list,GET]
  #companies
  list_companies: [/companies,\App\Controllers\homeController.listCompanies,GET]
  list_plans: [/plans/:id,\App\Controllers\homeController.listPlans,GET]
  #policies










