base_path: /
routes:
  index: [/,App\Controllers\homeController.index,GET]
  get_agents : [/agents,App\Controllers\agentsController.index,GET]
  get_collectors: ['/collectors',App\Controllers\agentsController.getCollectors,GET]
  get_client_list: [/clients/list,App\Controllers\clientsController.index,GET]
  update_client_profile: [/clients/:id/update,App\Controllers\clientsController.updatePolicy,PUT]
  create_payment: [/payments/create,\App\Controllers\agentsController.createPayment,POST]
  get_payment_list: [/payments,\App\Controllers\paymentsController.index,GET]
  validate_payment: [/payments/validate/:id,\App\Controllers\paymentsController.validate,GET]
  show_client: [/clients/show/:id,App\Controllers\clientsController.profile,GET]
  get_client_profile: [/clients/:id,App\Controllers\clientsController.show,GET]
  create_client: [/clients/create,App\Controllers\clientsController.create,POST]
  create_bulk_clients: [/clients/bulk,App\Controllers\clientsController.bulk,POST]
  get_reports_list: [/reports,\App\Controllers\reportsController.getReports,GET]
  create_expense: [/expenses,\App\Controllers\expensesController.create,POST]
  get_expenses_list: [/expenses,\App\Controllers\expensesController.index,GET]
  test: [/test,\App\Controllers\reportsController.payments_per_company,GET]
  accounts: [/accounts,\App\Controllers\homeController.listAccounts,GET]
  create_policy_payment: [/payments/policy,\App\Controllers\expensesController.CreatePolicyPayment,POST]
  create_transfer: [/transfers,\App\Controllers\operationsController.createTransfer,POST]
  list_checks: [/checks,\App\Controllers\homeController.listChecks,GET]
  collect_check: [/checks/collect,\App\Controllers\operationsController.collect_check,POST]







