base_path: /
routes:
  index: [/,App\Controllers\homeController.index,GET]
  get_agents : [/agents,App\Controllers\agentsController.index,GET]
  get_collectors: ['/collectors',App\Controllers\agentsController.getCollectors,GET]
  create_client: [/clients/create,App\Controllers\clientsController.create,POST]
  create_bulk_clients: [/clients/bulk,App\Controllers\clientsController.bulk,POST]









